name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: Frogobox ID

on:

  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          output-path: my-app.apk
          browserstack-upload: false
          ruby-version: "2.7.5"
          bundler-version: "2.3.26"
          fastlane-env: "debug"